FROM fedora:30

WORKDIR /persist
RUN mkdir -p /persist && yum update -y \
    && yum install -y make git qt5-devel gcc-c++ ruby ruby-devel python3 python3-devel which \
    && echo ". /persist/bin/mybashrc" >> /etc/bashrc
